### ISSUE TITLE
Test failure with JDK 9

### ISSUE THREAD

**Issue by lhuygi** [HuygensING/timbuctoo#135]
This is the test failure I reported earlier. Turns out that my Maven installation was trying to use JDK 9 instead of 8. 8 works fine. Feel free to close if JDK 9 is not supported, I'm setting my JAVA_HOME.

Anyway:

```
$ mvn -v
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 9-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-9-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-59-generic", arch: "amd64", family: "unix"
```

`mvn clean package` spits out 200kB of warnings, including:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running nl.knaw.huygens.timbuctoo.rdf.RdfImporterTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.413 sec <<< FAILURE! - in nl.knaw.huygens.timbuctoo.rdf.RdfImporterTest
importRdfReloadsTheDatabaseConfigurationAfterImport(nl.knaw.huygens.timbuctoo.rdf.RdfImporterTest)  Time elapsed: 5.397 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
    at nl.knaw.huygens.timbuctoo.rdf.RdfImporterTest.importRdfReloadsTheDatabaseConfigurationAfterImport(RdfImporterTest.java:30)
Caused by: java.lang.RuntimeException: Error starting org.neo4j.test.TestGraphDatabaseFactory$1$1, timbuctoo/timbuctoo-instancev4/target/test-data/impermanent-db
    at nl.knaw.huygens.timbuctoo.rdf.RdfImporterTest.importRdfReloadsTheDatabaseConfigurationAfterImport(RdfImporterTest.java:30)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@584f5497' was successfully initialized, but failed to start. Please see attached cause exception.
    at nl.knaw.huygens.timbuctoo.rdf.RdfImporterTest.importRdfReloadsTheDatabaseConfigurationAfterImport(RdfImporterTest.java:30)
Caused by: java.lang.IllegalAccessError: class org.neo4j.io.pagecache.impl.SingleFilePageSwapper (in unnamed module @0x1e04fa0a) cannot access class sun.nio.ch.FileChannelImpl (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x1e04fa0a
    at nl.knaw.huygens.timbuctoo.rdf.RdfImporterTest.importRdfReloadsTheDatabaseConfigurationAfterImport(RdfImporterTest.java:30)
```

and lots more of that.

**Comment by jauco** [comment]
Check. I'm going to close this. Java 9 is pre-release and the bug is a bug in neo4j so I'm going to let them fix it.

I checked and we have documented our dependency on java 8.
