### ISSUE TITLE
Adding a dataset with capitalised name renders an error

### ISSUE THREAD

**Issue by LvanWissen** [HuygensING/timbuctoo#333]
#### Steps to Reproduce
 1. Login
 2. Go to /account/datasets
 3. Add a new dataset by clicking the Add... button
 4. Enter a dataset name with a capital letter, e.g. 'Test'.
 
#### Expected/Desired behaviour
A dataset with this name should be added

#### Actual behaviour
```
Something went wrong.
A internal server error has occurred, try again later.
```

#### Extra info
Adding a dataset with name 'test' works. 

The log output as written to the screen (terminal, having it running in a compose stack):
```
timbuctoo_1      | - INFO   >     OPTIONS http://localhost:8088/v5/graphql [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
timbuctoo_1      | - INFO   < 200 OPTIONS http://localhost:8088/v5/graphql (24 bytes) (1/0 ms) [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
timbuctoo_1      | - INFO   >     POST http://localhost:8088/v5/graphql [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
timbuctoo_1      | - INFO   < 200 POST http://localhost:8088/v5/graphql (93 bytes) (6/5 ms) [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
timbuctoo_1      | - INFO   >     POST http://localhost:8088/v5/graphql [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
timbuctoo_1      | - INFO   < 200 POST http://localhost:8088/v5/graphql (584 bytes) (7 ms) [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
timbuctoo_1      | - INFO   >     POST http://localhost:8088/v5/graphql [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
timbuctoo_1      | - WARN   Exception while fetching data (/createDataSet) : Data set id is not supported: Owner id and dataSet id should start with a-z and be followed by a-z0-9 or 1 consecutive underscore. It must not end in an underscore. It must be at least 2 characters long. [graphql.execution.SimpleDataFetcherExceptionHandler]
timbuctoo_1      | java.lang.RuntimeException: Data set id is not supported: Owner id and dataSet id should start with a-z and be followed by a-z0-9 or 1 consecutive underscore. It must not end in an underscore. It must be at least 2 characters long.
timbuctoo_1      | 	at nl.knaw.huygens.timbuctoo.v5.graphql.mutations.CreateDataSetMutation.executeAction(CreateDataSetMutation.java:40)
timbuctoo_1      | 	at nl.knaw.huygens.timbuctoo.v5.graphql.mutations.Mutation.get(Mutation.java:17)
timbuctoo_1      | 	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86)
timbuctoo_1      | 	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:261)
timbuctoo_1      | 	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
timbuctoo_1      | 	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:175)
timbuctoo_1      | 	at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43)
timbuctoo_1      | 	at graphql.execution.Async.eachSequentiallyImpl(Async.java:75)
timbuctoo_1      | 	at graphql.execution.Async.eachSequentially(Async.java:64)
timbuctoo_1      | 	at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:38)
timbuctoo_1      | 	at graphql.execution.Execution.executeOperation(Execution.java:159)
timbuctoo_1      | 	at graphql.execution.Execution.execute(Execution.java:101)
timbuctoo_1      | 	at graphql.GraphQL.execute(GraphQL.java:573)
timbuctoo_1      | 	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:515)
timbuctoo_1      | 	at graphql.GraphQL.executeAsync(GraphQL.java:489)
timbuctoo_1      | 	at graphql.GraphQL.execute(GraphQL.java:420)
timbuctoo_1      | 	at nl.knaw.huygens.timbuctoo.v5.dropwizard.endpoints.GraphQl.executeGraphql(GraphQl.java:189)
timbuctoo_1      | 	at nl.knaw.huygens.timbuctoo.v5.dropwizard.endpoints.GraphQl.postJson(GraphQl.java:104)
timbuctoo_1      | 	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
timbuctoo_1      | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
timbuctoo_1      | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
timbuctoo_1      | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
timbuctoo_1      | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
timbuctoo_1      | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
timbuctoo_1      | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
timbuctoo_1      | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
timbuctoo_1      | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
timbuctoo_1      | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
timbuctoo_1      | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
timbuctoo_1      | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
timbuctoo_1      | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
timbuctoo_1      | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
timbuctoo_1      | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
timbuctoo_1      | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
timbuctoo_1      | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
timbuctoo_1      | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
timbuctoo_1      | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
timbuctoo_1      | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
timbuctoo_1      | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
timbuctoo_1      | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
timbuctoo_1      | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
timbuctoo_1      | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
timbuctoo_1      | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
timbuctoo_1      | 	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
timbuctoo_1      | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
timbuctoo_1      | 	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
timbuctoo_1      | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
timbuctoo_1      | 	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
timbuctoo_1      | 	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
timbuctoo_1      | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
timbuctoo_1      | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
timbuctoo_1      | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
timbuctoo_1      | 	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
timbuctoo_1      | 	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)
timbuctoo_1      | 	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
timbuctoo_1      | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
timbuctoo_1      | 	at org.eclipse.jetty.server.Server.handle(Server.java:502)
timbuctoo_1      | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
timbuctoo_1      | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
timbuctoo_1      | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
timbuctoo_1      | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
timbuctoo_1      | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
timbuctoo_1      | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
timbuctoo_1      | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
timbuctoo_1      | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
timbuctoo_1      | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
timbuctoo_1      | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
timbuctoo_1      | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
timbuctoo_1      | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
timbuctoo_1      | 	at java.base/java.lang.Thread.run(Unknown Source)
timbuctoo_1      | - INFO   < 200 POST http://localhost:8088/v5/graphql (352 bytes) (15/14 ms) [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]

```

**Comment by MMaas3** [comment]
We are working on documentation, that will explain to you how to you can change the title of a data set. In the mean time I can point you to the `setDataSetMetadata` in the GraphQL api. You can find a query interface with autocomplete at `http://localhost:8088/static/graphiql`. We will come back to you when we have the documentation ready, planned for the next two weeks.

**Comment by robzeeman** [comment]
The error is caused by a constraint on the dataset ID, which is a combination of the dataset name and the ID of the owner. For publication purposes the field Title is used. 
Adding and changing the title and other metadata fields can be done with GraphQL. (See the [documentation](https://github.com/HuygensING/timbuctoo/blob/master/documentation/timbuctoo-graphql-api-guide.adoc#editing-metadata-information-in-a-timbuctoo-dataset) on this.)

Since GraphQL can be quite a fuzz for most users, we're working on a new user interface in which an editor and hyperlinked browser are included as well as a form for creating new datasets. In this environment the problem will also be fixed, by a more stringent validation.
